### ISSUE TITLE
Module »PHPBrowser« not found

### ISSUE THREAD

**Issue by pixelbrackets** [lucatume/codeception-steppify#2]
Hey,

thanks for this package! :)

When I run the example command to steppify the »PHPBrowser« module I get an error:

    $ codecept gherkin:steppify PHPBrowser
    Module '\Codeception\Module\PHPBrowser' does not exist.

When I see the [list of Codeception modules](https://github.com/Codeception/Codeception/tree/2.3/src/Codeception/Module), then the module is written in CamelCase. Using this writing the command works:

    $ codecept gherkin:steppify PhpBrowser
    Generating Gherkin steps from module '\Codeception\Module\PhpBrowser...'

I suggest changing this in the [README](https://github.com/lucatume/codeception-steppify/blob/master/README.md).

**Comment by lucatume** [comment]
Thanks for reporting the issue *and* providing a fix; I've merged it.
